### ISSUE TITLE
Enable scrolling

### ISSUE THREAD

**Issue by Sydrimon** [Sydrimon/wurstball-viewer#19]
When zooming into a picture you can only see the centre.
There is no scrolling with the mouse wheel or navigation with the arrows.

**Comment by jpitchardu** [comment]
I can help you with this

**Comment by Sydrimon** [comment]
Of course! Please go ahead and have fun.

**Comment by jpitchardu** [comment]
Thanks, I'll notify you of any progress.

**Comment by jpitchardu** [comment]
I'm working on this, I've one question, with the scrolling it will only move vertically, should I add scroll bars? or use shift + scroll to move it horizontally?

**Comment by jpitchardu** [comment]
Fixed Here https://github.com/Sydrimon/wurstball-viewer/pull/23
