### ISSUE TITLE
Current config branch throws NPE on startup

### ISSUE THREAD

**Issue by offa** [Sydrimon/wurstball-viewer#4]
The current `config`-Branch throws an `NullPointerException` on application start.
### Related Stacktrace

```
Caused by: java.lang.NullPointerException
    at wurstball.data.WurstballData.<init>(WurstballData.java:31)
    at wurstball.data.WurstballData.<clinit>(WurstballData.java:27)
    ... 10 more
```
### Reproduce
1. Checkout & build `config` Branch (at a2b82fc)
2. Run application
### Possible fix
1. Drop singletons (at least for the configuration part)
2. Load / create the config an Application start (`Application.init()` best?)
3. Pass the loaded object to it's users

**Comment by Sydrimon** [comment]
**Fixed**
Since it's not finished I never tested the `config`-branch :sweat_smile:
Not the singleton was the problem but the constructor of `WurstballData` doing the second step before the first.
Thanks

**Comment by offa** [comment]
Yep, current commit works :+1:
